name: 'atymic/deployer-php-action'
description: 'Set up Deployer PHP for use in github actions'
inputs:
    ssh-private-key:
        description: 'SSH key to use during the deployment'
        required: true
    ssh-known-hosts:
        description: 'SSH known hosts file '
        required: false
    ssh-disable-host-key-checking:
        description: 'Turn off host key checking (insecure!)'
        required: false
    deloyer-version:
        description: 'Version of deployer to install'
        required: false
    deloyer-recipes-version:
        description: 'Version of deployer recipes to install'
        required: false
    deloyer-skip-install:
        description: 'Skip install of deployer (if you are using a locally installed version)'
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
branding:
    icon: server
    color: 'yellow'
